language: cpp

env:
  global:
    - CXXFLAGS='-O0'

jobs:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: focal
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - os: osx
      osx_image: xcode11
  allow_failures:
    - os: osx
      osx_image: xcode11

script:
  - autoreconf
  - mkdir build && cd build
  - ../configure --enable-{compact,const,linear,lookahead,ngram}-fsts --enable-{compress,far,mpdt,pdt,special,bin}
  - make -j2
  - make check
