sudo: required
dist: bionic
language: cpp

env:
  global:
    - CXXFLAGS='-O0'

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx
      osx_image: xcode11
  allow_failures:
    - os: osx
      osx_image: xcode11

script:
  - autoreconf
  - mkdir build && cd build
  - ../configure --enable-{compact,const,linear,lookahead,ngram}-fsts --enable-{compress,far,mpdt,pdt,special,bin}
  - make -j2
  - make check
